"use client";

import { useActionState, useMemo, useState } from "react";
import { readSheet, type CellValue } from "read-excel-file/browser";
import { createReceivable, importReceivables, recordPayment, setFinanceAccess, updateFinancePolicy, voidPayment, voidReceivable, type FinanceState } from "@/app/panel/propiedades/[propertyId]/cartera/actions";
import { Button } from "@/components/ui/button";

const inputClass="mt-2 h-11 w-full rounded-lg border bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-ring";
const labelClass="block text-sm font-medium";
function Result({state}:{state:FinanceState}){if(state?.error)return <p role="alert" className="text-sm text-destructive">{state.error}</p>;if(state?.success)return <p role="status" className="text-sm text-primary">{state.success}</p>;return null;}
export type FinanceUnit={id:string;label:string};

export function ReceivableForm({propertyId,units,defaultUnitId}:{propertyId:string;units:FinanceUnit[];defaultUnitId?:string}){
  const [state,action,pending]=useActionState(createReceivable,undefined as FinanceState);const today=new Date().toISOString().slice(0,10);
  return <form action={action} className="grid gap-4"><input type="hidden" name="propertyId" value={propertyId}/><label className={labelClass}>Apartamento<select className={inputClass} name="unitId" defaultValue={defaultUnitId??""} required><option value="" disabled>Selecciona</option>{units.map((unit)=><option key={unit.id} value={unit.id}>{unit.label}</option>)}</select></label><label className={labelClass}>Concepto<input className={inputClass} name="concept" minLength={2} maxLength={180} placeholder="Administración octubre" required/></label><div className="grid gap-4 sm:grid-cols-3"><label className={labelClass}>Valor (COP)<input className={inputClass} name="amount" type="number" min="0.01" step="0.01" required/></label><label className={labelClass}>Fecha de emisión<input className={inputClass} name="issuedOn" type="date" defaultValue={today} required/></label><label className={labelClass}>Vencimiento<input className={inputClass} name="dueOn" type="date" min={today} required/></label></div><label className={labelClass}>Referencia externa opcional<input className={inputClass} name="externalReference" maxLength={120}/></label><div className="flex flex-wrap items-center gap-4"><Button disabled={pending}>{pending?"Registrando…":"Registrar obligación"}</Button><Result state={state}/></div></form>;
}

export type OpenReceivable={id:string;concept:string;dueOn:string;outstanding:number};
export function PaymentForm({propertyId,unitId,receivables}:{propertyId:string;unitId:string;receivables:OpenReceivable[]}){
  const [state,action,pending]=useActionState(recordPayment,undefined as FinanceState);const [amount,setAmount]=useState("");const [allocations,setAllocations]=useState<Record<string,string>>({});const allocated=useMemo(()=>Object.values(allocations).reduce((sum,value)=>sum+(Number(value)||0),0),[allocations]);
  function applyOldest(){let remaining=Number(amount)||0;const next:Record<string,string>={};for(const item of [...receivables].sort((a,b)=>a.dueOn.localeCompare(b.dueOn))){const value=Math.min(remaining,item.outstanding);if(value>0)next[item.id]=value.toFixed(2);remaining-=value;}setAllocations(next);}
  return <form action={action} className="grid gap-4"><input type="hidden" name="propertyId" value={propertyId}/><input type="hidden" name="unitId" value={unitId}/><div className="grid gap-4 sm:grid-cols-3"><label className={labelClass}>Valor recibido (COP)<input className={inputClass} name="amount" type="number" min="0.01" step="0.01" value={amount} onChange={(event)=>setAmount(event.target.value)} required/></label><label className={labelClass}>Fecha del pago<input className={inputClass} name="paidOn" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label className={labelClass}>Referencia<input className={inputClass} name="reference" maxLength={120}/></label></div><div className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">Distribución del pago</p><p className="text-xs text-muted-foreground">Asignado {allocated.toLocaleString("es-CO",{style:"currency",currency:"COP"})}</p></div><Button type="button" variant="outline" size="sm" onClick={applyOldest} disabled={!amount}>Aplicar a las más antiguas</Button></div><div className="mt-4 grid gap-3">{receivables.map((item)=><label key={item.id} className="grid items-center gap-3 rounded-lg bg-secondary/60 p-3 text-sm sm:grid-cols-[1fr_10rem]"><span>{item.concept} · vence {item.dueOn} · saldo {item.outstanding.toLocaleString("es-CO",{style:"currency",currency:"COP"})}</span><span><input type="hidden" name="receivableId" value={item.id}/><input className="h-10 w-full rounded-lg border bg-white px-3" name={`allocation_${item.id}`} type="number" min="0" max={item.outstanding} step="0.01" value={allocations[item.id]??""} onChange={(event)=>setAllocations({...allocations,[item.id]:event.target.value})} placeholder="0"/></span></label>)}{!receivables.length&&<p className="text-sm text-muted-foreground">No hay obligaciones con saldo pendiente.</p>}</div></div><div className="flex flex-wrap items-center gap-4"><Button disabled={pending||allocated>(Number(amount)||0)}>{pending?"Registrando…":"Registrar pago"}</Button><Result state={state}/></div></form>;
}

export function FinancePolicyForm({propertyId,restrict,days}:{propertyId:string;restrict:boolean;days:number}){const[state,action,pending]=useActionState(updateFinancePolicy,undefined as FinanceState);const[enabled,setEnabled]=useState(restrict);return <form action={action} className="grid gap-4"><input type="hidden" name="propertyId" value={propertyId}/><label className="flex items-center gap-3 text-sm font-medium"><input type="checkbox" name="restrictReservations" checked={enabled} onChange={(event)=>setEnabled(event.target.checked)}/>Restringir reservas cuando la unidad alcance el umbral</label><label className={labelClass}>Días mínimos de mora<input className={`${inputClass} max-w-52`} name="minimumOverdueDays" type="number" min={0} max={3650} defaultValue={days} required/></label>{enabled&&<label className="flex items-start gap-3 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><input className="mt-1" type="checkbox" name="balancesConfirmed" required/>Confirmo que los saldos vigentes de la propiedad ya fueron cargados.</label>}<div className="flex flex-wrap items-center gap-4"><Button disabled={pending}>{pending?"Guardando…":"Guardar política"}</Button><Result state={state}/></div></form>}

export function FinanceAccessForm({propertyId,membershipId,enabled}:{propertyId:string;membershipId:string;enabled:boolean}){const[state,action,pending]=useActionState(setFinanceAccess,undefined as FinanceState);return <form action={action} className="flex flex-wrap items-center gap-3"><input type="hidden" name="propertyId" value={propertyId}/><input type="hidden" name="unitMembershipId" value={membershipId}/><input type="hidden" name="enabled" value={enabled?"false":"true"}/><Button size="sm" variant={enabled?"outline":"default"} disabled={pending}>{pending?"Guardando…":enabled?"Retirar acceso":"Habilitar cartera"}</Button><Result state={state}/></form>}

export function VoidReceivableForm({propertyId,unitId,receivableId}:{propertyId:string;unitId:string;receivableId:string}){const[state,action,pending]=useActionState(voidReceivable,undefined as FinanceState);return <form action={action} className="mt-3 flex flex-wrap items-end gap-3"><input type="hidden" name="propertyId" value={propertyId}/><input type="hidden" name="unitId" value={unitId}/><input type="hidden" name="receivableId" value={receivableId}/><label className={`${labelClass} min-w-64 flex-1`}>Motivo de anulación<input className={inputClass} name="reason" minLength={3} maxLength={500} required/></label><Button size="sm" variant="outline" disabled={pending}>{pending?"Anulando…":"Anular obligación"}</Button><Result state={state}/></form>}
export function VoidPaymentForm({propertyId,unitId,paymentId}:{propertyId:string;unitId:string;paymentId:string}){const[state,action,pending]=useActionState(voidPayment,undefined as FinanceState);return <form action={action} className="mt-3 flex flex-wrap items-end gap-3"><input type="hidden" name="propertyId" value={propertyId}/><input type="hidden" name="unitId" value={unitId}/><input type="hidden" name="paymentId" value={paymentId}/><label className={`${labelClass} min-w-64 flex-1`}>Motivo de anulación<input className={inputClass} name="reason" minLength={3} maxLength={500} required/></label><Button size="sm" variant="outline" disabled={pending}>{pending?"Anulando…":"Anular pago"}</Button><Result state={state}/></form>}

function normalize(value:CellValue|null){return String(value??"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g,"_")}
export function ImportReceivablesForm({propertyId}:{propertyId:string}){const[state,action,pending]=useActionState(importReceivables,undefined as FinanceState);const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState<string[][]>([]);const[previewError,setPreviewError]=useState("");async function selectFile(selected?:File){setFile(selected??null);setPreview([]);setPreviewError("");if(!selected)return;try{if(!selected.name.toLowerCase().endsWith(".xlsx")||selected.size>2*1024*1024)throw new Error("Selecciona un .xlsx de máximo 2 MB.");const rows=await readSheet(selected);const headers=rows[0]?.map(normalize)??[];const required=["torre","apartamento","concepto","valor","fecha_emision","fecha_vencimiento","referencia","tipo"];if(required.some((name)=>!headers.includes(name)))throw new Error("El archivo no corresponde a la plantilla de cartera.");if(rows.length<2||rows.length>501)throw new Error("Incluye entre 1 y 500 filas de datos.");setPreview(rows.slice(0,6).map((row)=>row.map((cell)=>cell instanceof Date?cell.toISOString().slice(0,10):String(cell??""))));}catch(error){setPreviewError(error instanceof Error?error.message:"No pudimos leer el archivo.");}}
return <form action={action} className="grid gap-5"><input type="hidden" name="propertyId" value={propertyId}/><label className={labelClass}>Archivo Excel<input className="mt-2 block w-full rounded-lg border bg-white p-3 text-sm" name="file" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(event)=>selectFile(event.target.files?.[0])} required/></label><p className="text-xs text-muted-foreground">Máximo 2 MB y 500 filas. Las referencias deben ser únicas.</p>{previewError&&<p role="alert" className="text-sm text-destructive">{previewError}</p>}{preview.length>0&&<div className="overflow-x-auto rounded-xl border"><table className="min-w-full text-left text-xs"><tbody>{preview.map((row,rowIndex)=><tr key={rowIndex} className={rowIndex===0?"bg-secondary font-semibold":"border-t"}>{row.map((cell,index)=><td key={index} className="whitespace-nowrap px-3 py-2">{cell}</td>)}</tr>)}</tbody></table><p className="border-t p-3 text-xs text-muted-foreground">Vista previa de las primeras {Math.max(preview.length-1,0)} filas. Al confirmar, el servidor vuelve a validar todo el archivo y guarda el lote completo o ninguno.</p></div>}<div className="flex flex-wrap items-center gap-4"><Button disabled={pending||!file||preview.length===0||Boolean(previewError)}>{pending?"Importando…":"Confirmar importación"}</Button><Result state={state}/></div></form>}
