import Link from "next/link";
import { notFound } from "next/navigation";
import { Button } from "@/components/ui/button";
import { assemblyStatusLabels, assemblyTypeLabel, rsvpLabels } from "@/lib/assemblies/constants";
import { requirePropertyMember } from "@/lib/auth/require-property-member";

type Attendee = { member_id: string; rsvp: string };
const formatter = new Intl.DateTimeFormat("es-CO", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Bogota" });

export default async function AssembliesPage({ params }: { params: Promise<{ propertyId: string }> }) {
  const { propertyId } = await params; const { supabase, membership, property } = await requirePropertyMember(propertyId); const isAdmin = membership.roles.includes("administrator");
  if (!isAdmin && !membership.roles.includes("member")) notFound();
  const { data } = await supabase.from("assemblies").select("id,type,title,starts_at,location,status,published_at,assembly_attendees(member_id,rsvp)").eq("property_id", propertyId).order("starts_at", { ascending: false });
  const assemblies = data ?? [];
  return <main className="mx-auto min-h-screen max-w-5xl px-5 py-8 sm:px-10"><header className="flex flex-wrap items-end justify-between gap-4 border-b pb-6"><div><Link href={`/panel/propiedades/${propertyId}/dashboard`} className="text-sm text-muted-foreground hover:text-foreground">← Panel de {property.name}</Link><p className="mt-5 text-xs font-semibold tracking-wider text-primary uppercase">Gobierno y participación</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Asambleas</h1><p className="mt-2 text-sm text-muted-foreground">{isAdmin ? "Publica convocatorias, registra asistencia y conserva el expediente privado." : "Consulta las convocatorias dirigidas a ti y confirma tu asistencia."}</p></div>{isAdmin && <Button asChild><Link href={`/panel/propiedades/${propertyId}/asambleas/nueva`}>Nueva asamblea</Link></Button>}</header><section className="mt-7 grid gap-4">{assemblies.length === 0 ? <div className="rounded-2xl border bg-card p-8 text-center text-sm text-muted-foreground">No hay asambleas visibles para tu cuenta.</div> : assemblies.map((item) => { const attendees = (item.assembly_attendees ?? []) as Attendee[]; const own = attendees.find((row) => row.member_id === membership.id); const status = item.status === "scheduled" && !item.published_at ? "draft" : item.status; return <Link key={item.id} href={`/panel/propiedades/${propertyId}/asambleas/${item.id}`} className="rounded-2xl border bg-card p-5 transition-colors hover:bg-muted/50"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold tracking-wider text-primary uppercase">{assemblyTypeLabel(item.type)}</p><h2 className="mt-2 text-lg font-semibold">{item.title}</h2><p className="mt-2 text-sm text-muted-foreground">{formatter.format(new Date(item.starts_at))} · {item.location}</p>{own && <p className="mt-2 text-xs text-muted-foreground">Tu respuesta: {rsvpLabels[own.rsvp]}</p>}</div><span className="rounded-full bg-secondary px-3 py-1 text-xs font-medium">{assemblyStatusLabels[status]}</span></div>{isAdmin && <p className="mt-3 text-xs text-muted-foreground">{attendees.length} convocado(s)</p>}</Link>; })}</section></main>;
}
