import Link from "next/link";
import { visitDateFormatter } from "@/lib/visitors/validation";
import { Button } from "@/components/ui/button";
import { requirePropertyMember } from "@/lib/auth/require-property-member";
import { visitKindLabel, visitStatusLabel } from "@/lib/visitors/constants";

type UnitRelation={code:string;buildings:{name:string}|{name:string}[]|null}|{code:string;buildings:{name:string}|{name:string}[]|null}[]|null;
function unitLabel(units:UnitRelation){const unit=Array.isArray(units)?units[0]:units;const building=Array.isArray(unit?.buildings)?unit.buildings[0]:unit?.buildings;return [building?.name,unit?.code].filter(Boolean).join(" · ")||"Apartamento";}

export default async function VisitsPage({params,searchParams}:{params:Promise<{propertyId:string}>;searchParams:Promise<{tipo?:string;estado?:string}>}){
  const {propertyId}=await params;const filters=await searchParams;const {supabase,membership,property}=await requirePropertyMember(propertyId);const formatter=visitDateFormatter(property.timezone);const canCreate=membership.roles.includes("member")&&!membership.roles.some((role:string)=>role==="administrator"||role==="concierge");
  let query=supabase.from("visitors").select("id,visitor_name,kind,service_type,people_count,status,scheduled_start,scheduled_end,units(code,buildings(name))").eq("property_id",propertyId).order("created_at",{ascending:false}).order("id",{ascending:false});if(filters.tipo==="maintenance"||filters.tipo==="personal")query=query.eq("kind",filters.tipo);if(["pending","rejected","authorized","entered","exited","cancelled"].includes(filters.estado??""))query=query.eq("status",filters.estado!);const {data:visits}=await query;
  const link=(label:string,href:string,active:boolean)=><Link href={href} className={`rounded-full px-3 py-1.5 text-xs font-medium ${active?"bg-primary text-white":"bg-secondary"}`}>{label}</Link>;
  return <main className="mx-auto min-h-screen max-w-5xl px-5 py-8 sm:px-10"><header className="flex flex-wrap items-end justify-between gap-4 border-b pb-6"><div><Link href={`/panel/propiedades/${propertyId}/dashboard`} className="text-sm text-muted-foreground hover:text-foreground">← Panel de {property.name}</Link><p className="mt-5 text-xs font-semibold tracking-wider text-primary uppercase">Control de acceso</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Visitas</h1><p className="mt-2 text-sm text-muted-foreground">Solicitudes de visitas personales y de mantenimiento, con revisión e historial de movimientos.</p></div>{canCreate&&<Button asChild><Link href={`/panel/propiedades/${propertyId}/visitas/nueva`}>Solicitar visita</Link></Button>}</header><div className="mt-6 flex flex-wrap gap-2">{link("Todas",`/panel/propiedades/${propertyId}/visitas`,!filters.tipo&&!filters.estado)}{link("Pendientes",`/panel/propiedades/${propertyId}/visitas?estado=pending`,filters.estado==="pending")}{link("Aceptadas",`/panel/propiedades/${propertyId}/visitas?estado=authorized`,filters.estado==="authorized")}{link("Dentro",`/panel/propiedades/${propertyId}/visitas?estado=entered`,filters.estado==="entered")}{link("Mantenimiento",`/panel/propiedades/${propertyId}/visitas?tipo=maintenance`,filters.tipo==="maintenance")}</div><section className="mt-6 grid gap-4">{(visits??[]).length===0?<div className="rounded-2xl border bg-card p-8 text-center text-sm text-muted-foreground">No hay visitas visibles con este filtro.</div>:visits?.map((visit)=><Link key={visit.id} href={`/panel/propiedades/${propertyId}/visitas/${visit.id}`} className="rounded-2xl border bg-card p-5 transition-colors hover:bg-muted/50"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold tracking-wider text-primary uppercase">{visitKindLabel(visit.kind)} · {unitLabel(visit.units as UnitRelation)}</p><h2 className="mt-2 text-lg font-semibold">{visit.visitor_name}</h2><p className="mt-1 text-sm text-muted-foreground">{visit.kind==="maintenance"&&visit.service_type?`${visit.service_type} · `:""}{visit.people_count} persona{visit.people_count===1?"":"s"}</p></div><span className="rounded-full bg-secondary px-3 py-1 text-xs font-medium">{visitStatusLabel(visit.status)}</span></div><p className="mt-3 text-xs text-muted-foreground">{formatter.format(new Date(visit.scheduled_start))} — {formatter.format(new Date(visit.scheduled_end))}</p></Link>)}</section></main>;
}
