import Link from "next/link";
import { CreateVisitForm,type VisitDirectoryRow } from "@/components/visitors/visit-forms";
import { requirePropertyMember } from "@/lib/auth/require-property-member";

type UnitLink={unit_id:string;units:{code:string;buildings:{name:string}|{name:string}[]|null}|{code:string;buildings:{name:string}|{name:string}[]|null}[]|null};
export default async function NewVisitPage({params}:{params:Promise<{propertyId:string}>}){
  const {propertyId}=await params;const {supabase,membership,property}=await requirePropertyMember(propertyId);const delegated=membership.roles.some((role:string)=>role==="administrator"||role==="concierge");let directory:VisitDirectoryRow[]=[];
  if(delegated){const {data,error}=await supabase.rpc("get_package_registration_directory",{target_property_id:propertyId});if(error)throw new Error("No se pudo cargar el directorio mínimo.");directory=(data??[]) as VisitDirectoryRow[];}else{const now=new Date().toISOString();const {data}=await supabase.from("unit_memberships").select("unit_id,units(code,buildings(name))").eq("property_id",propertyId).eq("member_id",membership.id).lte("valid_from",now).or(`valid_to.is.null,valid_to.gt.${now}`);directory=((data??[]) as UnitLink[]).map((link)=>{const unit=Array.isArray(link.units)?link.units[0]:link.units;const building=Array.isArray(unit?.buildings)?unit.buildings[0]:unit?.buildings;return{unit_id:link.unit_id,unit_code:unit?.code??"Unidad",building_name:building?.name??"Torre",member_id:membership.id,display_name:"Tú"};});}
  return <main className="mx-auto min-h-screen max-w-2xl px-5 py-8 sm:px-10"><Link href={`/panel/propiedades/${propertyId}/visitas`} className="text-sm text-muted-foreground hover:text-foreground">← Visitas de {property.name}</Link><section className="mt-6 rounded-2xl border bg-card p-6 sm:p-8"><p className="text-xs font-semibold tracking-wider text-primary uppercase">Nueva autorización</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Registrar visita</h1><p className="mt-2 mb-7 text-sm text-muted-foreground">La entrada solo podrá registrarse dentro de la ventana indicada.</p>{directory.length?<CreateVisitForm propertyId={propertyId} directory={directory} delegated={delegated}/>:<p className="rounded-xl bg-secondary p-4 text-sm">No hay apartamentos y anfitriones activos disponibles.</p>}</section></main>;
}
