import Link from "next/link";
import { notFound } from "next/navigation";
import { AssemblyDocumentUpload, AssemblyStatusForm, AttendanceForm, PublishAssemblyForm, RepresentationForm, RepresentationReviewForm, RsvpForm, UpdateAssemblyForm } from "@/components/assemblies/assembly-forms";
import { assemblyStatusLabels, assemblyTypeLabel, attendanceLabels, representationStatusLabels, rsvpLabels } from "@/lib/assemblies/constants";
import { requirePropertyMember } from "@/lib/auth/require-property-member";

type Agenda = { id: string; position: number; title: string; description: string | null };
type ProfileRelation = { display_name: string } | { display_name: string }[] | null;
type MemberRelation = { profiles: ProfileRelation } | { profiles: ProfileRelation }[] | null;
type UnitRelation = { code: string; buildings: { name: string } | { name: string }[] | null } | { code: string; buildings: { name: string } | { name: string }[] | null }[] | null;
type Attendee = { id: string; member_id: string; unit_id: string; rsvp: string; responded_at: string | null; attendance_status: string; attended_at: string | null; attendance_note: string | null; property_members: MemberRelation; units: UnitRelation };
type Representation = { id: string; unit_id: string; grantor_member_id: string; representative_member_id: string | null; external_representative_name: string | null; status: string; review_note: string | null; property_members: MemberRelation; representative: MemberRelation; units: UnitRelation };
type DocumentRow = { id: string; original_name: string; size_bytes: number; document_kind: string; version: number; assembly_id: string | null; assembly_representation_id: string | null };
type EventRow = { id: string; event_type: string; description: string | null; occurred_at: string };
const dateTime = new Intl.DateTimeFormat("es-CO", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Bogota" });
const eventLabels: Record<string, string> = { assembly_created: "Borrador creado", assembly_published: "Convocatoria publicada", assembly_updated: "Información actualizada", assembly_rsvp_changed: "Respuesta de asistencia actualizada", assembly_attendance_recorded: "Asistencia registrada", assembly_representation_submitted: "Representación registrada", assembly_representation_reviewed: "Representación revisada", assembly_document_added: "Documento añadido", assembly_started: "Asamblea iniciada", assembly_finished: "Asamblea finalizada", assembly_cancelled: "Asamblea cancelada" };
function one<T>(value: T | T[] | null | undefined): T | null { return Array.isArray(value) ? value[0] ?? null : value ?? null; }
function memberName(value: MemberRelation) { return one(one(value)?.profiles)?.display_name ?? "Miembro"; }
function unitName(value: UnitRelation) { const unit = one(value), building = one(unit?.buildings); return [building?.name, unit?.code].filter(Boolean).join(" · ") || "Apartamento"; }

export default async function AssemblyDetailPage({ params, searchParams }: { params: Promise<{ propertyId: string; assemblyId: string }>; searchParams: Promise<{ created?: string }> }) {
  const { propertyId, assemblyId } = await params; const { supabase, membership, property } = await requirePropertyMember(propertyId); const isAdmin = membership.roles.includes("administrator");
  const [{ data: item }, { data: agendaData }, { data: attendeeData }, { data: representationData }, { data: documentData }, { data: eventData }, { data: ownUnitData }, { data: optionData }] = await Promise.all([
    supabase.from("assemblies").select("id,property_id,type,title,description,starts_at,location,status,published_at,finished_at,cancelled_at,cancellation_reason,created_at").eq("property_id", propertyId).eq("id", assemblyId).maybeSingle(),
    supabase.from("assembly_agenda").select("id,position,title,description").eq("property_id", propertyId).eq("assembly_id", assemblyId).order("position"),
    supabase.from("assembly_attendees").select("id,member_id,unit_id,rsvp,responded_at,attendance_status,attended_at,attendance_note,property_members!assembly_attendees_property_id_member_id_fkey(profiles!property_members_user_id_fkey(display_name)),units!assembly_attendees_property_id_unit_id_fkey(code,buildings(name))").eq("property_id", propertyId).eq("assembly_id", assemblyId),
    supabase.from("assembly_representations").select("id,unit_id,grantor_member_id,representative_member_id,external_representative_name,status,review_note,property_members!assembly_representations_property_id_grantor_member_id_fkey(profiles!property_members_user_id_fkey(display_name)),representative:property_members!assembly_representations_property_id_representative_member_id_fkey(profiles!property_members_user_id_fkey(display_name)),units(code,buildings(name))").eq("property_id", propertyId).eq("assembly_id", assemblyId).order("created_at", { ascending: false }),
    supabase.from("documents").select("id,original_name,size_bytes,document_kind,version,assembly_id,assembly_representation_id").eq("property_id", propertyId).eq("status", "available").or(`assembly_id.eq.${assemblyId},assembly_representation_id.not.is.null`).order("created_at"),
    supabase.from("activity_events").select("id,event_type,description,occurred_at").eq("property_id", propertyId).eq("assembly_id", assemblyId).order("occurred_at", { ascending: false }),
    supabase.from("unit_memberships").select("unit_id,units(code,buildings(name))").eq("property_id", propertyId).eq("member_id", membership.id).lte("valid_from", new Date().toISOString()).or(`valid_to.is.null,valid_to.gt.${new Date().toISOString()}`),
    supabase.rpc("get_assembly_representative_options", { target_assembly_id: assemblyId }),
  ]);
  if (!item) notFound();
  const agenda = (agendaData ?? []) as Agenda[], attendees = (attendeeData ?? []) as unknown as Attendee[], representations = (representationData ?? []) as unknown as Representation[];
  const documents = (documentData ?? []) as DocumentRow[], events = (eventData ?? []) as EventRow[]; const ownAttendee = attendees.find((row) => row.member_id === membership.id); const derivedStatus = item.status === "scheduled" && !item.published_at ? "draft" : item.status; const isFuture = new Date(item.starts_at) > new Date();
  const ownUnits = (ownUnitData ?? []).map((row) => ({ id: row.unit_id, label: unitName(row.units as UnitRelation) })); const representativeOptions = ((optionData ?? []) as { member_id: string; display_name: string }[]).filter((row) => row.member_id !== membership.id).map((row) => ({ id: row.member_id, name: row.display_name }));
  const assemblyDocuments = documents.filter((row) => row.assembly_id === item.id); const created = (await searchParams).created === "1";
  return <main className="mx-auto min-h-screen max-w-6xl px-5 py-8 sm:px-10"><Link href={`/panel/propiedades/${propertyId}/asambleas`} className="text-sm text-muted-foreground hover:text-foreground">← Asambleas de {property.name}</Link>{created && <p role="status" className="mt-5 rounded-xl bg-secondary p-4 text-sm font-medium text-primary">Borrador creado. Revisa los datos, adjunta la convocatoria y publícalo cuando esté listo.</p>}<header className="mt-6 rounded-2xl border bg-card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold tracking-wider text-primary uppercase">{assemblyTypeLabel(item.type)}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{item.title}</h1><p className="mt-3 text-sm text-muted-foreground">{dateTime.format(new Date(item.starts_at))} · {item.location}</p></div><span className="rounded-full bg-secondary px-3 py-1 text-sm font-medium">{assemblyStatusLabels[derivedStatus]}</span></div>{item.description && <p className="mt-5 whitespace-pre-wrap text-sm leading-6">{item.description}</p>}{item.cancellation_reason && <p className="mt-5 rounded-xl bg-secondary p-4 text-sm"><strong>Motivo de cancelación:</strong> {item.cancellation_reason}</p>}{ownAttendee && <div className="mt-5 rounded-xl border p-4"><p className="text-sm font-medium">Tu confirmación: {rsvpLabels[ownAttendee.rsvp]}</p>{item.status === "scheduled" && isFuture && <div className="mt-3"><RsvpForm propertyId={propertyId} assemblyId={assemblyId} /></div>}</div>}</header>
  {isAdmin && <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-card p-6"><h2 className="text-xl font-semibold">Administrar convocatoria</h2><div className="mt-5"><UpdateAssemblyForm propertyId={propertyId} assembly={item} /></div>{derivedStatus === "draft" && <div className="mt-5 border-t pt-5"><PublishAssemblyForm propertyId={propertyId} assemblyId={assemblyId} /></div>}</div>{item.published_at && <div className="rounded-2xl border bg-card p-6"><h2 className="text-xl font-semibold">Estado operativo</h2><p className="mt-2 mb-5 text-sm text-muted-foreground">Inicia la asamblea desde dos horas antes. La cancelación conserva todo el expediente.</p><AssemblyStatusForm propertyId={propertyId} assemblyId={assemblyId} status={item.status} /></div>}</section>}
  <div className="mt-6 grid gap-6 lg:grid-cols-[1.3fr_1fr]"><div className="grid gap-6"><section className="rounded-2xl border bg-card p-6"><h2 className="text-xl font-semibold">Orden del día</h2><ol className="mt-5 grid gap-3">{agenda.map((point) => <li key={point.id} className="flex gap-3 rounded-xl border p-4"><span className="font-semibold text-primary">{point.position}.</span><div><p className="font-medium">{point.title}</p>{point.description && <p className="mt-1 text-sm text-muted-foreground">{point.description}</p>}</div></li>)}</ol></section>
  <section className="rounded-2xl border bg-card p-6"><h2 className="text-xl font-semibold">Documentos privados</h2><div className="mt-4 grid gap-2">{assemblyDocuments.length ? assemblyDocuments.map((document) => <a key={document.id} href={`/api/assemblies/documents/${document.id}`} className="rounded-lg border px-4 py-3 text-sm hover:bg-muted">{document.original_name} <span className="text-muted-foreground">· versión {document.version} · {(Number(document.size_bytes) / 1024).toFixed(0)} KB</span></a>) : <p className="text-sm text-muted-foreground">No hay documentos publicados.</p>}</div>{isAdmin && item.status !== "cancelled" && <div className="mt-5 grid gap-5 border-t pt-5"><div><p className="mb-3 text-sm font-medium">Convocatoria</p><AssemblyDocumentUpload assemblyId={assemblyId} kind="convocation" /></div><div><p className="mb-3 text-sm font-medium">Soporte</p><AssemblyDocumentUpload assemblyId={assemblyId} kind="support" /></div>{item.status === "finished" && <div><p className="mb-3 text-sm font-medium">Acta</p><AssemblyDocumentUpload assemblyId={assemblyId} kind="minutes" /></div>}</div>}</section>
  {isAdmin && <section className="rounded-2xl border bg-card p-6"><h2 className="text-xl font-semibold">Convocados y asistencia</h2><div className="mt-5 grid gap-4">{attendees.map((attendee) => <article key={attendee.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{memberName(attendee.property_members)}</p><p className="text-xs text-muted-foreground">{unitName(attendee.units)} · RSVP: {rsvpLabels[attendee.rsvp]}</p></div><span className="rounded-full bg-secondary px-3 py-1 text-xs">{attendanceLabels[attendee.attendance_status]}</span></div>{new Set(["in_progress", "finished"]).has(item.status) && <div className="mt-4"><AttendanceForm propertyId={propertyId} assemblyId={assemblyId} attendeeId={attendee.id} current={attendee.attendance_status} /></div>}</article>)}</div></section>}</div>
  <aside className="grid content-start gap-6"><section className="rounded-2xl border bg-card p-6"><h2 className="text-xl font-semibold">Representaciones</h2><p className="mt-2 text-sm text-muted-foreground">Documentan el poder presentado. No conceden automáticamente voto ni quórum.</p>{!isAdmin && item.status === "scheduled" && isFuture && ownUnits.length > 0 && <details className="mt-5"><summary className="cursor-pointer text-sm font-medium">Registrar una representación</summary><div className="mt-4"><RepresentationForm propertyId={propertyId} assemblyId={assemblyId} units={ownUnits} members={representativeOptions} /></div></details>}<div className="mt-5 grid gap-4">{representations.map((representation) => { const evidence = documents.filter((document) => document.assembly_representation_id === representation.id); return <article key={representation.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{memberName(representation.property_members)}</p><p className="text-xs text-muted-foreground">{unitName(representation.units)} · representa: {representation.external_representative_name ?? memberName(representation.representative)}</p></div><span className="rounded-full bg-secondary px-2 py-1 text-xs">{representationStatusLabels[representation.status]}</span></div>{representation.review_note && <p className="mt-3 text-sm text-muted-foreground">{representation.review_note}</p>}<div className="mt-3 grid gap-2">{evidence.map((document) => <a key={document.id} href={`/api/assemblies/documents/${document.id}`} className="text-sm text-primary hover:underline">{document.original_name}</a>)}</div>{representation.status === "submitted" && <div className="mt-4"><AssemblyDocumentUpload assemblyId={assemblyId} representationId={representation.id} kind="representation_evidence" availableSlots={Math.max(0, 5 - evidence.length)} /></div>}{isAdmin && new Set(["submitted", "validated"]).has(representation.status) && <div className="mt-4 border-t pt-4"><RepresentationReviewForm propertyId={propertyId} assemblyId={assemblyId} representationId={representation.id} status={representation.status} /></div>}</article>; })}{!representations.length && <p className="text-sm text-muted-foreground">No hay representaciones visibles.</p>}</div></section>
  <section className="rounded-2xl border bg-card p-6"><h2 className="text-xl font-semibold">Historial</h2><ol className="mt-5 grid gap-4">{events.map((event) => <li key={event.id} className="border-l-2 border-primary/30 pl-4"><p className="text-sm font-medium">{eventLabels[event.event_type] ?? event.description}</p><time className="mt-1 block text-xs text-muted-foreground">{dateTime.format(new Date(event.occurred_at))}</time></li>)}</ol></section></aside></div></main>;
}
