"use client";

import { useActionState, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { changeAssemblyStatus, createAssembly, publishAssembly, recordAssemblyAttendance, reviewAssemblyRepresentation, setAssemblyRsvp, submitAssemblyRepresentation, updateAssembly, type AssemblyActionState } from "@/app/panel/propiedades/[propertyId]/asambleas/actions";
import { Button } from "@/components/ui/button";
import { assemblyTypes } from "@/lib/assemblies/constants";
import { createClient } from "@/lib/supabase/client";

export type AssemblyDirectoryRow = { unit_id: string; unit_code: string; building_name: string; member_id: string; display_name: string };
const inputClass = "mt-2 h-11 w-full rounded-lg border bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-ring";
const areaClass = "mt-2 min-h-28 w-full rounded-lg border bg-white px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-ring";
const labelClass = "block text-sm font-medium";
function Result({ state }: { state: AssemblyActionState }) { if (state?.error) return <p role="alert" className="text-sm text-destructive">{state.error}</p>; if (state?.success) return <p role="status" className="text-sm text-primary">{state.success}</p>; return null; }

export function CreateAssemblyForm({ propertyId, directory }: { propertyId: string; directory: AssemblyDirectoryRow[] }) {
  const [state, action, pending] = useActionState(createAssembly, undefined as AssemblyActionState);
  const grouped = useMemo(() => Array.from(new Map(directory.map((row) => [row.unit_id, { unitId: row.unit_id, label: `${row.building_name} · ${row.unit_code}`, members: directory.filter((item) => item.unit_id === row.unit_id) }])).values()), [directory]);
  return <form action={action} className="grid gap-5"><input type="hidden" name="propertyId" value={propertyId} />
    <div className="grid gap-5 sm:grid-cols-2"><label className={labelClass}>Tipo<select className={inputClass} name="type" defaultValue="ordinary">{assemblyTypes.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className={labelClass}>Fecha y hora<input className={inputClass} type="datetime-local" name="startsAt" required /></label></div>
    <label className={labelClass}>Título<input className={inputClass} name="title" minLength={4} maxLength={180} required placeholder="Asamblea general ordinaria" /></label>
    <label className={labelClass}>Lugar o enlace<input className={inputClass} name="location" minLength={3} maxLength={240} required placeholder="Salón comunal" /></label>
    <label className={labelClass}>Descripción<textarea className={areaClass} name="description" maxLength={5000} placeholder="Información adicional para los convocados." /></label>
    <label className={labelClass}>Orden del día<textarea className={areaClass} name="agenda" required placeholder={"Escribe un punto por línea\nVerificación de asistentes\nInforme de administración\nProposiciones"} /><span className="mt-2 block text-xs text-muted-foreground">Cada línea se guardará como un punto ordenado.</span></label>
    <fieldset className="rounded-xl border p-4"><legend className="px-2 text-sm font-medium">Convocados explícitos</legend><div className="mt-2 grid max-h-80 gap-4 overflow-y-auto">{grouped.map((unit) => <div key={unit.unitId}><p className="text-sm font-semibold">{unit.label}</p><div className="mt-2 grid gap-2">{unit.members.map((member) => <label key={member.member_id} className="flex items-center gap-3 text-sm"><input type="checkbox" name="audience" value={`${member.member_id}|${member.unit_id}`} className="size-4 accent-primary" />{member.display_name}</label>)}</div></div>)}</div>{!grouped.length && <p className="text-sm text-muted-foreground">No hay miembros con apartamentos vigentes.</p>}</fieldset>
    <p className="text-xs text-muted-foreground">Se creará un borrador. Podrás revisarlo y adjuntar la convocatoria antes de publicarlo.</p><div className="flex items-center gap-4"><Button disabled={pending || !grouped.length}>{pending ? "Creando…" : "Crear borrador"}</Button><Result state={state} /></div>
  </form>;
}

function SimpleAction({ action, propertyId, assemblyId, children, hidden }: { action: (state: AssemblyActionState, data: FormData) => Promise<AssemblyActionState>; propertyId: string; assemblyId: string; children: React.ReactNode; hidden?: Record<string, string> }) {
  const [state, formAction, pending] = useActionState(action, undefined as AssemblyActionState);
  return <form action={formAction} className="grid gap-3"><input type="hidden" name="propertyId" value={propertyId} /><input type="hidden" name="assemblyId" value={assemblyId} />{Object.entries(hidden ?? {}).map(([name, value]) => <input key={name} type="hidden" name={name} value={value} />)}<Button variant="outline" disabled={pending}>{pending ? "Guardando…" : children}</Button><Result state={state} /></form>;
}

export function PublishAssemblyForm(props: { propertyId: string; assemblyId: string }) { return <SimpleAction action={publishAssembly} {...props}>Publicar convocatoria</SimpleAction>; }
export function RsvpForm({ propertyId, assemblyId }: { propertyId: string; assemblyId: string }) { const [state, action, pending] = useActionState(setAssemblyRsvp, undefined as AssemblyActionState); return <form action={action} className="flex flex-wrap items-center gap-3"><input type="hidden" name="propertyId" value={propertyId} /><input type="hidden" name="assemblyId" value={assemblyId} /><Button name="rsvp" value="yes" disabled={pending}>Asistiré</Button><Button name="rsvp" value="no" variant="outline" disabled={pending}>No asistiré</Button><Result state={state} /></form>; }

export function UpdateAssemblyForm({ propertyId, assembly }: { propertyId: string; assembly: { id: string; title: string; description: string | null; starts_at: string; location: string } }) {
  const [state, action, pending] = useActionState(updateAssembly, undefined as AssemblyActionState);
  const localDate = new Date(assembly.starts_at); localDate.setMinutes(localDate.getMinutes() - localDate.getTimezoneOffset());
  return <form action={action} className="grid gap-4"><input type="hidden" name="propertyId" value={propertyId} /><input type="hidden" name="assemblyId" value={assembly.id} /><label className={labelClass}>Título<input className={inputClass} name="title" defaultValue={assembly.title} required /></label><div className="grid gap-4 sm:grid-cols-2"><label className={labelClass}>Fecha y hora<input className={inputClass} type="datetime-local" name="startsAt" defaultValue={localDate.toISOString().slice(0, 16)} required /></label><label className={labelClass}>Lugar<input className={inputClass} name="location" defaultValue={assembly.location} required /></label></div><label className={labelClass}>Descripción<textarea className={areaClass} name="description" defaultValue={assembly.description ?? ""} /></label><div className="flex items-center gap-4"><Button variant="outline" disabled={pending}>{pending ? "Actualizando…" : "Guardar cambios"}</Button><Result state={state} /></div></form>;
}

export function AssemblyStatusForm({ propertyId, assemblyId, status }: { propertyId: string; assemblyId: string; status: string }) {
  const [state, action, pending] = useActionState(changeAssemblyStatus, undefined as AssemblyActionState); const [target, setTarget] = useState(status === "scheduled" ? "in_progress" : "finished");
  if (!new Set(["scheduled", "in_progress"]).has(status)) return null;
  return <form action={action} className="grid gap-4"><input type="hidden" name="propertyId" value={propertyId} /><input type="hidden" name="assemblyId" value={assemblyId} /><label className={labelClass}>Acción<select className={inputClass} name="status" value={target} onChange={(event) => setTarget(event.target.value)}>{status === "scheduled" && <><option value="in_progress">Iniciar asamblea</option><option value="cancelled">Cancelar asamblea</option></>}{status === "in_progress" && <option value="finished">Finalizar asamblea</option>}</select></label>{target === "cancelled" && <label className={labelClass}>Motivo<textarea className={areaClass} name="reason" minLength={4} required /></label>}<div className="flex items-center gap-4"><Button variant="outline" disabled={pending}>{pending ? "Actualizando…" : "Aplicar cambio"}</Button><Result state={state} /></div></form>;
}

export function AttendanceForm({ propertyId, assemblyId, attendeeId, current }: { propertyId: string; assemblyId: string; attendeeId: string; current: string }) {
  const [state, action, pending] = useActionState(recordAssemblyAttendance, undefined as AssemblyActionState); const correction = current !== "pending";
  return <form action={action} className="grid gap-2 sm:grid-cols-[auto_1fr_auto]"><input type="hidden" name="propertyId" value={propertyId} /><input type="hidden" name="assemblyId" value={assemblyId} /><input type="hidden" name="attendeeId" value={attendeeId} /><select className="h-9 rounded-lg border bg-white px-2 text-sm" name="attended" defaultValue={current === "present" ? "true" : "false"}><option value="true">Presente</option><option value="false">Ausente</option></select><input className="h-9 rounded-lg border bg-white px-2 text-sm" name="note" minLength={correction ? 4 : undefined} required={correction} placeholder={correction ? "Motivo de la corrección" : "Nota opcional"} /><Button size="sm" variant="outline" disabled={pending}>Guardar</Button><div className="sm:col-span-3"><Result state={state} /></div></form>;
}

export function RepresentationForm({ propertyId, assemblyId, units, members }: { propertyId: string; assemblyId: string; units: { id: string; label: string }[]; members: { id: string; name: string }[] }) {
  const [state, action, pending] = useActionState(submitAssemblyRepresentation, undefined as AssemblyActionState); const [mode, setMode] = useState("member");
  return <form action={action} className="grid gap-4"><input type="hidden" name="propertyId" value={propertyId} /><input type="hidden" name="assemblyId" value={assemblyId} /><label className={labelClass}>Apartamento<select className={inputClass} name="unitId" required><option value="">Selecciona</option>{units.map((unit) => <option key={unit.id} value={unit.id}>{unit.label}</option>)}</select></label><label className={labelClass}>Tipo de representante<select className={inputClass} value={mode} onChange={(event) => setMode(event.target.value)}><option value="member">Miembro de la propiedad</option><option value="external">Persona externa</option></select></label>{mode === "member" ? <label className={labelClass}>Representante<select className={inputClass} name="representativeMemberId" required><option value="">Selecciona</option>{members.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label> : <label className={labelClass}>Nombre completo<input className={inputClass} name="externalName" minLength={3} maxLength={120} required /></label>}<p className="text-xs text-muted-foreground">Después de guardar, adjunta el poder en PDF, JPG o PNG. La administración debe validarlo.</p><div className="flex items-center gap-4"><Button variant="outline" disabled={pending}>{pending ? "Creando…" : "Registrar representación"}</Button><Result state={state} /></div></form>;
}

export function RepresentationReviewForm({ propertyId, assemblyId, representationId, status }: { propertyId: string; assemblyId: string; representationId: string; status: string }) {
  const [state, action, pending] = useActionState(reviewAssemblyRepresentation, undefined as AssemblyActionState); const options = status === "submitted" ? [["validated", "Validar"], ["rejected", "Rechazar"]] : [["revoked", "Revocar"]];
  return <form action={action} className="grid gap-2"><input type="hidden" name="propertyId" value={propertyId} /><input type="hidden" name="assemblyId" value={assemblyId} /><input type="hidden" name="representationId" value={representationId} /><select className="h-9 rounded-lg border bg-white px-2 text-sm" name="status">{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input className="h-9 rounded-lg border bg-white px-2 text-sm" name="note" minLength={4} required placeholder="Nota obligatoria" /><Button size="sm" variant="outline" disabled={pending}>Guardar decisión</Button><Result state={state} /></form>;
}

type PreparedUpload = { documentId: string; path: string; token: string };
export function AssemblyDocumentUpload({ assemblyId, representationId, kind, availableSlots = 5 }: { assemblyId: string; representationId?: string; kind: "convocation" | "support" | "minutes" | "representation_evidence"; availableSlots?: number }) {
  const router = useRouter(), inputRef = useRef<HTMLInputElement>(null); const [busy, setBusy] = useState(false), [message, setMessage] = useState<string>();
  async function upload() { const files = Array.from(inputRef.current?.files ?? []); if (!files.length || files.length > availableSlots) return setMessage(`Selecciona entre 1 y ${availableSlots} archivo(s).`); setBusy(true); setMessage(undefined); try { for (const file of files) { const response = await fetch("/api/assemblies/attachments", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "prepare", assemblyId, representationId, kind, name: file.name, mimeType: file.type, size: file.size }) }); const prepared = await response.json() as PreparedUpload & { error?: string }; if (!response.ok) throw new Error(prepared.error ?? "No se pudo preparar el archivo."); const supabase = createClient(); const { error } = await supabase.storage.from("private-documents").uploadToSignedUrl(prepared.path, prepared.token, file, { contentType: file.type }); if (error) throw new Error("No se pudo subir el archivo."); const completedResponse = await fetch("/api/assemblies/attachments", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "finalize", documentId: prepared.documentId }) }); const completed = await completedResponse.json() as { error?: string }; if (!completedResponse.ok) throw new Error(completed.error ?? "El archivo no superó la validación."); } if (inputRef.current) inputRef.current.value = ""; setMessage("Documento cargado y validado."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo cargar el archivo."); } finally { setBusy(false); } }
  if (availableSlots < 1) return <p className="text-sm text-muted-foreground">Se alcanzó el máximo de cinco archivos.</p>;
  return <div className="grid gap-3"><input ref={inputRef} type="file" multiple accept="application/pdf,image/jpeg,image/png" disabled={busy} className="block w-full text-sm" /><p className="text-xs text-muted-foreground">Hasta {availableSlots} archivo(s), 10 MB cada uno.</p><div className="flex items-center gap-3"><Button type="button" size="sm" variant="outline" onClick={upload} disabled={busy}>{busy ? "Validando…" : "Subir"}</Button>{message && <p role="status" className="text-sm">{message}</p>}</div></div>;
}
