import Link from "next/link";
import { redirect } from "next/navigation";
import { Banknote, Bell, BookOpenCheck, Boxes, Building2, CalendarDays, ChartNoAxesCombined, CircleParking, DoorOpen, FileWarning, House, KeyRound, MessageSquareText, Package, UsersRound, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DashboardModules, MetricCard, type DashboardModule } from "@/components/dashboard/role-dashboard";
import { requirePropertyMember } from "@/lib/auth/require-property-member";

type View = "residente" | "porteria" | "administracion";
function residentModules(propertyId: string): DashboardModule[] { return [
  { title: "Paquetes", description: "Consulta paquetes recibidos y su estado de entrega.", icon: Package, href: `/panel/propiedades/${propertyId}/paquetes` }, { title: "Reservas", description: "Revisa zonas comunes, disponibilidad y reservas.", icon: CalendarDays }, { title: "Visitas", description: "Autoriza visitantes y servicios de mantenimiento.", icon: DoorOpen }, { title: "PQRS", description: "Crea solicitudes y sigue sus respuestas.", icon: MessageSquareText, href: `/panel/propiedades/${propertyId}/pqrs` }, { title: "Cartera", description: "Consulta la información financiera autorizada de tu unidad.", icon: Banknote }, { title: "Llamados", description: "Revisa llamados de atención dirigidos a ti.", icon: FileWarning }, { title: "Asambleas", description: "Consulta convocatorias y confirma asistencia.", icon: BookOpenCheck }, { title: "Notificaciones", description: "Encuentra las novedades de tu comunidad.", icon: Bell },
]; }
function conciergeModules(propertyId: string): DashboardModule[] { return [
  { title: "Paquetes", description: "Registra recepciones y entregas.", icon: Package, href: `/panel/propiedades/${propertyId}/paquetes` }, { title: "Visitas", description: "Consulta visitantes autorizados.", icon: DoorOpen }, { title: "Mantenimiento", description: "Revisa servicios técnicos autorizados.", icon: Wrench }, { title: "Ingresos", description: "Registra entradas con la autorización correspondiente.", icon: KeyRound }, { title: "Salidas", description: "Completa el registro de salida.", icon: CircleParking }, { title: "Reservas", description: "Consulta reservas vigentes de zonas comunes.", icon: CalendarDays },
]; }
function adminModules(propertyId: string): DashboardModule[] { return [
  { title: "Residentes", description: "Gestiona miembros, roles y vínculos con apartamentos.", icon: UsersRound, href: `/panel/propiedades/${propertyId}/miembros` }, { title: "Propiedad", description: "Administra los datos generales de la comunidad.", icon: Building2, href: `/panel/propiedades/${propertyId}` }, { title: "Apartamentos", description: "Gestiona torres, apartamentos, pisos y estados.", icon: House, href: `/panel/propiedades/${propertyId}/estructura` }, { title: "PQRS", description: "Gestiona solicitudes, responsables y estados.", icon: MessageSquareText, href: `/panel/propiedades/${propertyId}/pqrs` }, { title: "Paquetes", description: "Consulta recepciones, avisos y entregas.", icon: Package, href: `/panel/propiedades/${propertyId}/paquetes` }, { title: "Reservas", description: "Administra disponibilidad y solicitudes.", icon: CalendarDays }, { title: "Cartera", description: "Consulta y actualiza obligaciones autorizadas.", icon: Banknote }, { title: "Llamados", description: "Registra y gestiona llamados de atención.", icon: FileWarning }, { title: "Asambleas", description: "Publica convocatorias y administra asistencia.", icon: BookOpenCheck }, { title: "Zonas", description: "Configura zonas comunes y horarios.", icon: Boxes }, { title: "Reportes", description: "Consulta indicadores operativos de la propiedad.", icon: ChartNoAxesCombined },
]; }

export default async function PropertyDashboardPage({ params, searchParams }: { params: Promise<{ propertyId: string }>; searchParams: Promise<{ vista?: string }> }) {
  const { propertyId } = await params;
  const { supabase, membership, property } = await requirePropertyMember(propertyId);
  const views: View[] = [];
  if (membership.roles.includes("member")) views.push("residente");
  if (membership.roles.includes("concierge")) views.push("porteria");
  if (membership.roles.includes("administrator")) views.push("administracion");
  const requested = (await searchParams).vista as View | undefined;
  const view = requested && views.includes(requested) ? requested : views.at(-1);
  if (!view) redirect("/panel");
  const [{ count: unitCount }, { count: memberCount }, { data: ownUnits }] = await Promise.all([
    supabase.from("units").select("id", { count: "exact", head: true }).eq("property_id", propertyId).eq("status", "active"),
    view === "administracion" ? supabase.from("property_members").select("id", { count: "exact", head: true }).eq("property_id", propertyId).eq("status", "active") : Promise.resolve({ count: null }),
    view === "residente" ? supabase.from("unit_memberships").select("relationship,units(code)").eq("property_id", propertyId).eq("member_id", membership.id).is("valid_to", null) : Promise.resolve({ data: [] }),
  ]);
  const units = ownUnits ?? [];
  const modules = view === "administracion" ? adminModules(propertyId) : view === "porteria" ? conciergeModules(propertyId) : residentModules(propertyId);
  const viewLabel = view === "administracion" ? "Administración" : view === "porteria" ? "Portería" : "Residente";
  return <main className="mx-auto min-h-screen max-w-7xl px-5 py-7 sm:px-10"><header className="flex flex-wrap items-center justify-between gap-4 border-b pb-6"><div><Link href="/panel" className="text-sm text-muted-foreground hover:text-foreground">← Mis comunidades</Link><p className="mt-5 text-xs font-semibold tracking-wider text-primary uppercase">Panel de {viewLabel}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{property.name}</h1><p className="mt-2 text-sm text-muted-foreground">{[property.address, property.city].filter(Boolean).join(" · ")}</p></div><div className="flex flex-wrap gap-2">{views.map((allowedView) => <Button key={allowedView} asChild size="sm" variant={allowedView === view ? "default" : "outline"}><Link href={`/panel/propiedades/${propertyId}/dashboard?vista=${allowedView}`}>{allowedView === "administracion" ? "Administración" : allowedView === "porteria" ? "Portería" : "Residente"}</Link></Button>)}</div></header><section className="my-7 grid gap-4 sm:grid-cols-3"><MetricCard label={view === "residente" ? "Apartamentos vinculados" : "Apartamentos activos"} value={view === "residente" ? units.length : unitCount ?? 0} /><MetricCard label="Rol actual" value={viewLabel} /><MetricCard label={view === "administracion" ? "Miembros activos" : "Comunidad"} value={view === "administracion" ? memberCount ?? 0 : "Activa"} /></section>{view === "residente" && units.length > 0 && <section className="mb-7 rounded-2xl border bg-secondary/60 p-5"><p className="text-xs font-semibold tracking-wider text-primary uppercase">Tus apartamentos</p><div className="mt-3 flex flex-wrap gap-2">{units.map((unit, index) => { const related = Array.isArray(unit.units) ? unit.units[0] : unit.units as { code?: string } | null; return <span key={`${related?.code}-${index}`} className="rounded-full bg-card px-3 py-1 text-sm">{related?.code ?? "Unidad"} · {unit.relationship === "owner" ? "Propietario" : "Residente"}</span>; })}</div></section>}<section><div className="mb-5"><p className="text-sm text-muted-foreground">Accesos disponibles para este rol</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">Funciones de {viewLabel.toLowerCase()}</h2></div><DashboardModules modules={modules} /></section></main>;
}
