import Link from "next/link";
import { Button } from "@/components/ui/button";
import { CancelReservationForm, DecisionForm } from "@/components/reservations/reservation-forms";
import { requirePropertyMember } from "@/lib/auth/require-property-member";
import { reservationStatusLabel } from "@/lib/reservations/constants";

type OperationalRow = { reservation_id: string; amenity_name: string; building_name: string; unit_code: string; requester_name: string; attendee_count: number; status: string; starts_at: string; ends_at: string };
type OwnRow = { id: string; attendee_count: number; status: string; starts_at: string; ends_at: string; hold_expires_at: string | null; decision_reason: string | null; amenities: { name: string } | { name: string }[] | null; units: { code: string; buildings: { name: string } | { name: string }[] | null } | { code: string; buildings: { name: string } | { name: string }[] | null }[] | null };
type DisplayRow = { id: string; amenity: string; unit: string; requester?: string; attendeeCount: number; status: string; startsAt: string; endsAt: string; holdExpiresAt?: string | null; reason?: string | null };
function one<T>(value:T|T[]|null){return Array.isArray(value)?value[0]:value;}

export default async function ReservationsPage({ params, searchParams }: { params: Promise<{ propertyId: string }>; searchParams: Promise<{ created?: string }> }) {
  const { propertyId } = await params;
  const { supabase, membership, property } = await requirePropertyMember(propertyId);
  await supabase.rpc("refresh_reservations", { target_property_id: propertyId });
  const administrator=membership.roles.includes("administrator"), concierge=membership.roles.includes("concierge"), resident=membership.roles.includes("member");
  let rows:DisplayRow[]=[];
  if(administrator||concierge){const from=new Date();from.setDate(from.getDate()-30);const to=new Date();to.setDate(to.getDate()+93);const {data,error}=await supabase.rpc("list_operational_reservations",{target_property_id:propertyId,target_from:from.toISOString(),target_to:to.toISOString()});if(error)throw error;rows=((data??[]) as OperationalRow[]).map((row)=>({id:row.reservation_id,amenity:row.amenity_name,unit:[row.building_name,row.unit_code].filter(Boolean).join(" · "),requester:row.requester_name,attendeeCount:row.attendee_count,status:row.status,startsAt:row.starts_at,endsAt:row.ends_at}));}
  else {const {data,error}=await supabase.from("reservations").select("id,attendee_count,status,starts_at,ends_at,hold_expires_at,decision_reason,amenities(name),units(code,buildings(name))").eq("property_id",propertyId).order("starts_at",{ascending:false}).limit(100);if(error)throw error;rows=((data??[]) as unknown as OwnRow[]).map((row)=>{const amenity=one(row.amenities),unit=one(row.units),building=one(unit?.buildings??null);return{id:row.id,amenity:amenity?.name??"Zona",unit:[building?.name,unit?.code].filter(Boolean).join(" · "),attendeeCount:row.attendee_count,status:row.status,startsAt:row.starts_at,endsAt:row.ends_at,holdExpiresAt:row.hold_expires_at,reason:row.decision_reason};});}
  const formatter=new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",timeStyle:"short",timeZone:property.timezone});
  const created=(await searchParams).created==="1";
  return <main className="mx-auto min-h-screen max-w-6xl px-5 py-8 sm:px-10"><header className="flex flex-wrap items-end justify-between gap-4 border-b pb-6"><div><Link href={`/panel/propiedades/${propertyId}/dashboard`} className="text-sm text-muted-foreground hover:text-foreground">← Panel de {property.name}</Link><p className="mt-5 text-xs font-semibold tracking-wider text-primary uppercase">Zonas comunes</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Reservas</h1><p className="mt-2 text-sm text-muted-foreground">{administrator?"Aprueba solicitudes y consulta la agenda completa.":concierge?"Consulta la agenda operativa de la propiedad.":"Consulta y administra tus propias reservas."}</p></div>{resident&&<Button asChild><Link href={`/panel/propiedades/${propertyId}/reservas/nueva`}>Nueva reserva</Link></Button>}</header>{created&&<p role="status" className="mt-6 rounded-xl border border-primary/30 bg-primary/5 p-4 text-sm text-primary">La reserva fue creada correctamente.</p>}<section className="mt-7 grid gap-4">{rows.length===0?<div className="rounded-2xl border bg-card p-8 text-center text-sm text-muted-foreground">No hay reservas visibles en este periodo.</div>:rows.map((row)=><article key={row.id} className="rounded-2xl border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold tracking-wider text-primary uppercase">{row.amenity}</p><h2 className="mt-2 text-lg font-semibold">{formatter.format(new Date(row.startsAt))} → {formatter.format(new Date(row.endsAt))}</h2><p className="mt-2 text-sm text-muted-foreground">{row.unit} · {row.attendeeCount} asistentes{row.requester?` · ${row.requester}`:""}</p>{row.status==="pending"&&row.holdExpiresAt&&<p className="mt-2 text-xs text-muted-foreground">La solicitud mantiene el horario hasta {formatter.format(new Date(row.holdExpiresAt))}.</p>}{row.reason&&<p className="mt-2 text-sm">Motivo: {row.reason}</p>}</div><span className="rounded-full bg-secondary px-3 py-1 text-xs font-medium">{reservationStatusLabel(row.status)}</span></div>{administrator&&row.status==="pending"&&<div className="mt-5 border-t pt-5"><DecisionForm propertyId={propertyId} reservationId={row.id}/></div>}{(administrator||(!concierge&&resident))&&["pending","approved"].includes(row.status)&&new Date(row.startsAt)>new Date()&&<details className="mt-5 border-t pt-4"><summary className="cursor-pointer text-sm font-medium">Cancelar reserva</summary><div className="mt-4"><CancelReservationForm propertyId={propertyId} reservationId={row.id}/></div></details>}</article>)}</section></main>;
}
