import Link from "next/link";
import { Button } from "@/components/ui/button";
import { requirePropertyMember } from "@/lib/auth/require-property-member";
import { categoryLabel, requestTypeLabel, statusLabel } from "@/lib/pqrs/constants";

type UnitRelation = { code: string; buildings: { name: string } | { name: string }[] | null } | { code: string; buildings: { name: string } | { name: string }[] | null }[] | null;
function unitLabel(units: UnitRelation) { const unit = Array.isArray(units) ? units[0] : units; const building = Array.isArray(unit?.buildings) ? unit.buildings[0] : unit?.buildings; return [building?.name, unit?.code].filter(Boolean).join(" · ") || "Apartamento"; }

export default async function PqrsPage({ params }: { params: Promise<{ propertyId: string }> }) {
  const { propertyId } = await params;
  const { supabase, membership, property } = await requirePropertyMember(propertyId);
  const { data: requests } = await supabase.from("pqrs").select("id,request_type,category,subject,status,created_at,units(code,buildings(name))").eq("property_id", propertyId).order("created_at", { ascending: false });
  return <main className="mx-auto min-h-screen max-w-5xl px-5 py-8 sm:px-10"><header className="flex flex-wrap items-end justify-between gap-4 border-b pb-6"><div><Link href={`/panel/propiedades/${propertyId}/dashboard`} className="text-sm text-muted-foreground hover:text-foreground">← Panel de {property.name}</Link><p className="mt-5 text-xs font-semibold tracking-wider text-primary uppercase">Módulo de atención</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">PQRS</h1><p className="mt-2 text-sm text-muted-foreground">Solicitudes privadas entre residentes y administración.</p></div>{membership.roles.includes("member") && <Button asChild><Link href={`/panel/propiedades/${propertyId}/pqrs/nuevo`}>Crear PQRS</Link></Button>}</header><section className="mt-7 grid gap-4">{(requests ?? []).length === 0 ? <div className="rounded-2xl border bg-card p-8 text-center text-sm text-muted-foreground">Todavía no hay PQRS visibles para tu cuenta.</div> : requests?.map((request) => <Link key={request.id} href={`/panel/propiedades/${propertyId}/pqrs/${request.id}`} className="rounded-2xl border bg-card p-5 transition-colors hover:bg-muted/50"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold tracking-wider text-primary uppercase">{requestTypeLabel(request.request_type)} · {categoryLabel(request.category)} · {unitLabel(request.units as UnitRelation)}</p><h2 className="mt-2 text-lg font-semibold">{request.subject}</h2></div><span className="rounded-full bg-secondary px-3 py-1 text-xs font-medium">{statusLabel(request.status)}</span></div><p className="mt-3 text-xs text-muted-foreground">Creada el {new Intl.DateTimeFormat("es-CO", { dateStyle: "medium", timeStyle: "short" }).format(new Date(request.created_at))}</p></Link>)}</section></main>;
}
